version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: amiguxus-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - amiguxus_postgres_data:/var/lib/postgresql/data
    networks:
      - amiguxus-net

  redis:
    image: redis:7-alpine
    container_name: amiguxus-redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - amiguxus_redis_data:/data
    networks:
      - amiguxus-net

  minio:
    image: minio/minio:latest
    container_name: amiguxus-minio
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - amiguxus_minio_data:/data
    networks:
      - amiguxus-net
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    networks:
      - amiguxus-net
    entrypoint: >
      /bin/sh -c "
      echo 'Aguardando MinIO ficar pronto...';
      sleep 5;
      /usr/bin/mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb local/amiguxus-pets --ignore-existing;
      echo 'Definindo política de acesso pública...';
      /usr/bin/mc anonymous set public local/amiguxus-pets;
      echo 'Configuração do MinIO concluída.';
      exit 0;
      "

volumes:
  amiguxus_postgres_data:
    driver: local
  amiguxus_redis_data:
    driver: local
  amiguxus_minio_data:
    driver: local

networks:
  amiguxus-net:
    driver: bridge
